[workspace]
authors = ["RegnDai <daiyuchi2003@gmail.com>"]
channels = ["conda-forge"]
name = "lab-fitness"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = ">=26.1.2,<27"
uv = ">=0.11.26,<0.12"
